version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: init.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: validate.sh
      timeout: 200
      runas: ubuntu
