name: github action codedeploy CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  S3_BUCKET_NAME: ghkdtlwns987-bucket

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Gradlew permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Make Directory
        run: mkdir dist

      - name: Copy jar
        run: cp ./build/libs/*.jar ./dist/

      - name: zip
        run: tar -zcvf deploy.tar.gz ./dist

      - name: Upload to S3
        with:
          AWS_ACCESS_KEY_ID: $
          AWS_SECRET_ACCESS_KEY: $
        run: |
          aws s3 cp \
          --region ap-northeast-1 \
          --acl private \
          ./deploy.tar.gz \
          s3://$S3_BUCKET_NAME/deploy.tar.gz  \
