name: github action codedeploy CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Gradlew permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Make Directory
        run: mkdir dist

      - name: Copy Jar
        run: mv ./build/libs/*.jar ./dist/

      - name: Move CodeDeploy Script
        run: mv ./codedeploy/* ./dist/

      - name: zip
        run: tar -zcvf deploy.tar.gz ./dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Upload to S3
        run: |
          aws s3 cp \
          --region ap-northeast-1 \
          --acl private \
          ./deploy.tar.gz \
          s3://ghkdtlwns987-bucket/deploy.tar.gz  \

      - name: Call CodeDeploy
        run: | 
          aws deploy create-deployment \
          --application-name ghkdtlwns987-codedeploy-app \
          --deployment-group-name ghkdtlwns987-deploy-group \
          --region ap-northeast-1 \
          --s3-location bucket=ghkdtlwns987-bucket,bundleType=tgz,key=$/deploy.tar.gz \

